services:
  ollama:
    image: ollama/ollama
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434
    
  streamlit-app:
    image: ai-demo-app:latest
    ports:
      - 8501:8501
